### ISSUE TITLE
Bitcoin with ssl and domain get 401 error response

### ISSUE THREAD

**Issue by harizzubir** [denpamusic/laravel-bitcoinrpc#24]
Hi there,

Before this, I already tried using this library to connect with my bitcoin node by using ip and custom ports and it was successful. Just now, im thinking about putting a domain and ssl cert to the connection and tried it but failed. It keep gives me error 401 when i tried getbalance command. 

When i put the domain and port on web browser, it gives me no error and this message displayed "JSONRPC server handles only POST requests" and i assume this is considered my jsonrpc connection from remote host successful as this also displayed when im using ip address and no ssl.

How to configure my bitcoind.php so that i can do connection with domain instead of ip address and how im gonna implement ssl on the connection ? I tried including ssl cert path in bitcoind.php but nothing happens. 

Kindly assist me on this matter

My setup:
Bitcoin node:
Core: Bitcoin Core Daemon version v0.18.0
OS: Ubuntu 18.04.3 LTS
SSL: certbot 0.31.0
Domain Handler: Cloudflare

Remote:
Laragon Lite
PHP 7.2
Windows 10

**Comment by denpamusic** [comment]
Bitcoin Core dropped direct support for RPC over SSL since version 12.0. Please see [changelog](https://bitcoin.org/en/release/v0.12.0#rpc-ssl-support-dropped) and consider using suggested method of securing connection through stunnel.

As for accessing bitcoind via domain, it's nothing special - you just specify following in your dot env file (first line if you want to use ssl):
```
BITCOIND_SCHEME=https
BITCOIND_HOST=example.com
```

Although I'm sure you already did this...
Your issue is actually probably related to cloudflare. Cloudflare blocks requests from laravel-bitcoinrpc client (or other api clients for that matter) when security features enabled, because it can't detect it as a proper browser.

You can circumvent this by delegating subdomain for api requests and configuring Page Rules for it as described in this [guide](https://support.cloudflare.com/hc/en-us/articles/200504045-Using-Cloudflare-with-your-API).

**Comment by harizzubir** [comment]
right now im adding a A record for the new subdomain via cloudflare. so if that blocks me, then ill need to add A record to the domain provider itself right?

**Comment by denpamusic** [comment]
Adding record to the domain provider is useless as long as domain is delegated to cloudflare.

In order to make you subdomain work, you should specify Page Rule for it (should be something like `api.example.com/*`) with settings from tutorial in my previous reply.

If you're unsure on how to use cloudflare's Page Rules, please refer to their documentation: https://support.cloudflare.com/hc/en-us/articles/218411427-Understanding-and-Configuring-Cloudflare-Page-Rules-Page-Rules-Tutorial-

**Comment by harizzubir** [comment]
one more thing, i manage to use domain and ssl for the connection and now i tried implementing ht authentication to the domain. 

on web browser, whenever i put the domain on  search bar it will prompt me for that username and password that ive set. but then i put the url with username and password on my configuration file, it will return the same 401 response.

Kindly assist me on this matter.

URL format that ive user : 
**https://username:password@domain.com:rpcport**

is this the correct way?

**Comment by denpamusic** [comment]
External HTTP Authentication is not supported by this package.

Bitcoin Daemon already using authentication via `rpcuser` and `rpcpassword` parameters in `bitcoin.conf`, it won't ask for you credentials when visiting through your browser since it's expects POST requests, but on proper POST it'll ask client this information.

BITCOIND_HOST MUST contain only host name without scheme or any credentials.

**Comment by harizzubir** [comment]
is there any other security implementation that i need to be considered other than ssl and domain integration to bitcoin nodes?

**Comment by denpamusic** [comment]
As far a network stuff concerned not really. SSL encryption via stunnel should be good enough. If you don't trust stunnel, SSH tunneling will work as well. Any of the above would be secure enough for mitigating MITM attacks.

Note that when using stunnel or SSH tunneling, requests be coming from localhost as far as Bitcoin Core concerned, so `rpcallowip` option in `bitcoin.conf` will have no effect and any connecting IP will be allowed. You can use your system firewall (e. g. iptables) to restrict access to node from trusted IPs only.

You should also think of some kind of rate-limiting on your client in order to not overwhelm Bitcoin node that has no rate limiting on its own and cause DoS.

Finally, please be aware that running node and client on separate machines is no more (it's actually less) secure that running both on the same, so it should be done only for easier scaling and better resource utilization, not better security.

**Comment by harizzubir** [comment]
so as far right now this issue should be resolved then. thanks for the explanation and assistance given.
