### ISSUE TITLE
Possible to use external server IP

### ISSUE THREAD

**Issue by reinierkors** [denpamusic/laravel-bitcoinrpc#5]
Hi, is it possible to use an external IP address instead of localhost?

**Comment by denpamusic** [comment]
Hi, it is possible to use external IP or hostname to reach daemon.
Just make sure that RPC port is open on remote.

**Comment by CryDeTaan** [comment]
You can specify allowed IP address.
Examples from the bitcoin.conf spec:
```
#rpcallowip=10.1.1.34/255.255.255.0
#rpcallowip=1.2.3.4/24
#rpcallowip=2001:db8:85a3:0:0:8a2e:370:7334/96
```
See here for more information:
https://en.bitcoin.it/wiki/Running_Bitcoin#Bitcoin.conf_Configuration_File

**Comment by CryDeTaan** [comment]
This can be closed, I just tested and works by specifying in .env

Remember to run `php artisan vendor:publish --provider="Denpa\Bitcoin\Providers\ServiceProvider"` for the config to be created so that you can specify your remote server in the .env file. 

This is how I did it in the .env based on the `config/bitcoind.php` file:
```
BITCOIND_HOST=10.0.0.139
BITCOIND_USER=exampleuser
BITCOIND_PASSWORD=examplepasswor
```

**Comment by denpamusic** [comment]
Yes, I believe above comments by me and @CryDeTaan  fully answer initial question, so I'll close this for now.
If you have any issues setting up remote rpc access don't hesitate to update this issue or write your questions directly to [gitter](https://gitter.im/laravel-bitcoinrpc/Lobby). Thanks!
